### ISSUE TITLE
Add `linux-firmware-valve` package

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [SQuantam-OS/Super-QuantamOS#16]

**Comment by GuestSneezeOSDev** [comment]
@LukeShortCloud by any chance you could port this package?

**Comment by LukeShortCloud** [comment]
@GuestSneezeOSDev What do you want to port the package to? `buildroot`? I briefly looked into it and it appears to be similar in concept to a Gentoo package for Portage but I don't have any experience with anything besides DEB, PKGBUILD, and RPM.

**Comment by LukeShortCloud** [comment]
I have a RPM spec for it here: https://github.com/playtron-os/rpm-specs-gaming/blob/main/valve-firmware/valve-firmware.spec

**Comment by GuestSneezeOSDev** [comment]
Thanks @LukeShortCloud that will be extremely useful since QuantamOS is based on `buildroot` which has `RPM` this was really useful

**Comment by GuestSneezeOSDev** [comment]
Since buildroot is giving me a hardtime i will recompile the package

**Comment by GuestSneezeOSDev** [comment]
I Just found out that busybox has RPM support so thats amazing
