### ISSUE TITLE
Add `surface` support

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [SQuantam-OS/Super-QuantamOS#18]
I Should be able to do this in the kernel config

**Comment by GuestSneezeOSDev** [comment]
i found this package by the name of https://github.com/linux-surface/surface-uefi-firmware maybe i could implement it to the package repo

**Comment by LukeShortCloud** [comment]
Here are some hints on how I added support for this in winesapOS:

- https://github.com/LukeShortCloud/winesapOS/tree/4.1.0-beta.2?tab=readme-ov-file#microsoft-surface-laptops
- https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-setup.sh#L293
- https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#arch

The `linux-fsync-nobara` kernel used by Bazzite, Nobara, and winesapOS include the patches from `linux-surface`. The biggest benefit is that it enables touchscreen support.

- https://pagure.io/kernel-fsync/tree/main
- https://aur.archlinux.org/packages?O=0&K=linux-fsync-nobara-bin

There is also `iptsd` and `libwacom-surface` for providing full pen support.

- https://github.com/linux-surface/iptsd
- https://aur.archlinux.org/packages/libwacom-surface

**Comment by GuestSneezeOSDev** [comment]
@LukeShortCloud Thank you so much for the Contributions to QuantamOS I can not thank you enough in how useful the source's you have gave me

**Comment by LukeShortCloud** [comment]
Glad to help!
