### ISSUE TITLE
[port] Port `git`

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [SQuantam-OS/Super-QuantamOS#2]

**Comment by GuestSneezeOSDev** [comment]
@Labsdj can you compile the code from src?

**Comment by Labsdj** [comment]
at this moment no

**Comment by GuestSneezeOSDev** [comment]
ok thanks anyway

**Comment by GuestSneezeOSDev** [comment]
building this requires `make` which we have preinstalled so i will leave the source code in the `root` folder
